### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by stefan-ctrl** [iskorotkov/bully-election#2]
Hi,

awesome work! 
You're bully-algorithm implementation looks good to me. I would like to use your code base for an evaluation of the bullying algorithm in k8s. In my upcoming thesis I'm comparing different leader election algorithms for use in k8s. So, it's not really about review your code, but rather evaluating the bully algorithm as such.

Could you add a license which indicates how your code can be used?
I'm afraid without one I can not use your work and would have to evaluate the bully algorithm based on another implementation.

Maybe this link can give some insides about software licenses: 
[https://choosealicense.com](https://choosealicense.com)
[No License](https://choosealicense.com/no-permission/)

Best Regards
Stefan

**Comment by iskorotkov** [comment]
Thank you, I've added MIT license.
